apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
spec:
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: loan
          ports:
            - containerPort: 8080