apiVersion: v1
kind: Service
metadata:
  name: loan
  namespace: default
  labels:
    app: loan
spec:
  selector:
    app: loan
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer